serviceAccount:
  podSecurityPolicy:
    enabled: true
    name: vmware-system-privileged

trino:
  serviceAccount:
    create: true
    name: trino
  service:
    type: LoadBalancer
    port: 8080
  env:
    - name: AWS_ACCESS_KEY_ID
      value:
    - name: AWS_SECRET_ACCESS_KEY
      value:
  additionalCatalogs:
    iceberg: |-
      connector.name=iceberg
      hive.metastore.uri=thrift://hive-metastore:9083
      iceberg.file-format=PARQUET
    hive-postgres: |-
      connector.name=postgresql
      connection-url=jdbc:postgresql://hive-metastore:5432/postgres
      connection-user=hive
      connection-password=hive