stage: staging
trino:
  env:
    - name: AWS_ACCESS_KEY_ID
      value: '9_RKID1\kolbj_accid'
    - name: AWS_SECRET_ACCESS_KEY
      value: '37srLbsvxHL383GBO3hyJ1UQFiT1'

  additionalCatalogs:
    iceberg: |-
      connector.name=iceberg
      hive.metastore.uri=thrift://hive-metastore:9083
      iceberg.file-format=PARQUET
    hive-postgres: |-
      connector.name=postgresql
      connection-url=jdbc:postgresql://hive-metastore:5432/postgres
      connection-user=hive
      connection-password=hive
  ingress:
    enabled: true
    hostName: trino-staging.tkpoc.it32.labor
    tls:
      enabled: true
      secretName: trino-staging-tls
      issuerRef:
        name: contour-ca-issuer
        kind: ClusterIssuer
        group: cert-manager.io
  additionalConfigProperties: |-
    http-server.https.enabled=true
    internal-communication.https.required=true
    internal-communication.shared-secret=BcWhBgOr7cCAzcjQAN+zRw==

  server:
    # setup LDAP config for coordinator
      coordinatorExtraConfig: |-
        http-server.authentication.type=PASSWORD
        http-server.process-forwarded=true
  coordinator:
    additionalConfigFiles:
      log.properties: |-
        io.trino.plugin.password.ldap=DEBUG
      password-authenticator.properties: |-
        password-authenticator.name=ldap
        ldap.url=ldap://ads05.rki.local:389
        ldap.allow-insecure=true
        ldap.user-base-dn=DC=rki,DC=local
        ldap.bind-dn=CN=LDAP-SEARCH,OU=User-nosync,OU=IT-Service,DC=rki,DC=local
        ldap.bind-password=8E2eHbjz
        ldap.user-bind-pattern=uid=${USER},OU=User,DC=rki,DC=local
        ldap.group-auth-pattern=sAMAccountName=${USER}
    additionalExposedPorts:
      - name: https
        servicePort: 8443
        port: 8443
        protocol: TCP

hiveMetaStore:
  enabled: true
  image: jakobjkolb/hive-metastore
  imagePullPolicy: Always
  managedDB: true
  S3Endpoint:
    s3Bucket: pockubernetes
    s3Prefix: /ifs/S3-Prod/poc
    awsAccessKeyId: '9_RKID1\kolbj_accid'
    awsSecretAccessKey: '37srLbsvxHL383GBO3hyJ1UQFiT1'
    customS3EndpointURL: http://10.15.147.50:9020
  service:
    type: LoadBalancer
    port: 9083
    externalDnsName: hive-metastore-staging.tkpoc.it32.labor
