serviceAccount:
  podSecurityPolicy:
    enabled: true
    name: vmware-system-privileged

trino:
  serviceAccount:
    create: true
    name: trino
  service:
    type: LoadBalancer
    port: 8080
  coordinator:
    resources:
      limits:
        ephemeral-storage: 1Gi
        memory: 3Gi
      requests:
        ephemeral-storage: 1Gi
        memory: 2Gi
  worker:
    resources:
      limits:
        ephemeral-storage: 1Gi
        memory: 3Gi
      requests:
        ephemeral-storage: 1Gi
        memory: 2Gi