stage: staging
trino:
  coordinator:
    resources:
      limits:
        ephemeral-storage: 1Gi
        memory: 3Gi
      requests:
        ephemeral-storage: 1Gi
        memory: 2Gi
  worker:
    resources:
      limits:
        ephemeral-storage: 1Gi
        memory: 3Gi
      requests:
        ephemeral-storage: 1Gi
        memory: 2Gi
