stage: staging
trino:
  env:
    - name: AWS_ACCESS_KEY_ID
      value: '9_RKID1\kolbj_accid'
    - name: AWS_SECRET_ACCESS_KEY
      value: '37srLbsvxHL383GBO3hyJ1UQFiT1'

  additionalCatalogs:
    iceberg: |-
      connector.name=iceberg
      hive.metastore.uri=thrift://hive-metastore:9083
      iceberg.file-format=PARQUET
    hive-postgres: |-
      connector.name=postgresql
      connection-url=jdbc:postgresql://hive-metastore:5432/postgres
      connection-user=hive
      connection-password=hive
  

hiveMetaStore:
  enabled: true
  image: jakobjkolb/hive-metastore
  imagePullPolicy: Always
  managedDB: true
  S3Endpoint:
    s3Bucket: pockubernetes
    s3Prefix: /ifs/S3-Prod/poc
    awsAccessKeyId: '9_RKID1\kolbj_accid'
    awsSecretAccessKey: '37srLbsvxHL383GBO3hyJ1UQFiT1'
    customS3EndpointURL: http://10.15.147.50:9020
  service:
    type: LoadBalancer
    port: 9083
    externalDnsName: hive-metastore-staging.tkpoc.it32.labor
