apiVersion: v1
kind: Service
metadata:
  name: hive-metastore
  labels:
    app: hive-metastore
    managed-by: {{ .Release.Service }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
  - port: 9083
    name: thrift
  - port: 5432
    name: postgresql
  selector:
    app: hive-metastore
  {{- if .Values.hiveMetaStore.service.type }}
  type: {{ .Values.hiveMetaStore.service.type }}
  {{- end }}
